[global]
basepath = "~/.gossamer/ksmcc"
log = "info"

[log]
core = ""
network = ""
rpc = "debug"
state = ""
runtime = ""
babe = ""
grandpa = ""
sync = ""

[init]
genesis-raw = "./chain/ksmcc/genesis-raw.json"

[account]
key = ""
unlock = ""

[core]
roles = 1
babe-authority = false
grandpa-authority = false

[network]
port = 7001
nobootstrap = false
nomdns = false

[rpc]
enabled = true
external = true
port = 8545
host = "localhost"
modules = ["system", "author", "chain", "state", "rpc"]
ws-port = 8546
ws = true
ws-external = true
